version: "3.9"

services:
  api:
    restart: always
    container_name: redis-login-api
    build: .
    environment:
      DB_DSN: "host=db user=postgres password=1234 dbname=redis_login sslmode=disable"
    ports:
      - "5000:5000"
    volumes:
      - .:/app/api
    depends_on:
      - redis
      - db

  redis:
    container_name: redis-login-redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data

  db:
    container_name: redis-login-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: redis_login
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  redis_data: {}
  db_data: {}


